### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by HA-JD** [CrazyStudent13/novelAI-tags-collection#1]
版本Node.js v18.8.0
npm install
npm run dev
然后出现报错
` WARN  Two component files resolving to the same name LayoutsPageError:                                       16:22:52

 - C:/Users/HAJD/Desktop/novelAI-tags-collection-main/components/layouts/pageError/404.vue
 - C:/Users/HAJD/Desktop/novelAI-tags-collection-main/components/layouts/pageError/401.vue

 WARN  Two component files resolving to the same name LayoutsPageError:                                       16:22:52

 - C:/Users/HAJD/Desktop/novelAI-tags-collection-main/components/layouts/pageError/500.vue
 - C:/Users/HAJD/Desktop/novelAI-tags-collection-main/components/layouts/pageError/401.vue

i Discovered Components: .nuxt/components/readme.md                                                           16:22:52
√ Builder initialized                                                                                         16:22:52
√ Nuxt files generated                                                                                        16:22:53

* Client █████████████████████████ building (10%) 1/2 modules 1 active
 node_modules\webpack-hot-middleware\client.js

* Server █████████████████████████ building (10%) 1/1 modules 0 active

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\HAJD\Desktop\novelAI-tags-collection-main\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\HAJD\Desktop\novelAI-tags-collection-main\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\HAJD\Desktop\novelAI-tags-collection-main\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\HAJD\Desktop\novelAI-tags-collection-main\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\HAJD\Desktop\novelAI-tags-collection-main\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\HAJD\Desktop\novelAI-tags-collection-main\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\HAJD\Desktop\novelAI-tags-collection-main\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\HAJD\Desktop\novelAI-tags-collection-main\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\HAJD\Desktop\novelAI-tags-collection-main\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\HAJD\Desktop\novelAI-tags-collection-main\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\HAJD\Desktop\novelAI-tags-collection-main\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}`

**Comment by CrazyStudent13** [comment]
export NODE_OPTIONS=--openssl-legacy-provider

应该是Node版本太高的问题，参考这个：https://www.jianshu.com/p/fc7674e8a84d
后续我会尝试修复一下

**Comment by HA-JD** [comment]
已经解决方式如下
powershell管理员输入$env:NODE_OPTIONS="--openssl-legacy-provider"
cd到目录运行就OK

**Comment by HA-JD** [comment]
![image](https://user-images.githubusercontent.com/47666701/196130334-1d2f5873-f55e-4627-ac58-9330d50e7372.png)
